engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Gemspec/RequiredRubyVersion:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - ruby

ratings:
  paths:
    - lib/**/*.rb

exclude_paths:
  - spec/**/*
  - examples/*.rb
