language: ruby

rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head

cache: bundler

before_install:
  - gem install bundler

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter

matrix:
  allow_failures:
    - rvm: ruby-head

